name: Checks
on:
  pull_request:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - name: Install nix
       uses: nixbuild/nix-quick-install-action@v30
       with:
        nix_on_tmpfs: true
     - name: Run Checks
       run: nix flake check
